version: 0.1
storage:
  s3:
    accesskey: ACCESS_KEY
    secretkey: SECRET_KEY
    region: eu-west-1
    bucket: BUCKET_NAME
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
