version: '3.9'
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    volumes:
      - ${CERT_PATH}:/certs/domain.crt
      - ${KEY_PATH}:/certs/domain.key
      - ${AUTH_PATH}:/auth
      - $PWD/config.yml:/etc/docker/registry/config.yml