version: '3'
services:
  sabnzbd:
    image: sabnzbd/sabnzbd
    volumes:
      - $HOME/Documents/sabnzbd_config:/datadir
      - $HOME/Downloads:/downloads
  sonarr:
    image: hotio/sonarr
    volumes:
      - $HOME/Downloads:/downloads
      - $HOME/Documents/sonarr_config/:/config
    links:
      - sabnzbd
  nginx:
    build: nginx/
    ports:
      - 80:80
    links:
      - sabnzbd
      - sonarr
